Update generator-generic-ossf-slsa3-publish.yml

diff --git a/.github/workflows/generator-generic-ossf-slsa3-publish.yml b/.github/workflows/generator-generic-ossf-slsa3-publish.yml
--- a/.github/workflows/generator-generic-ossf-slsa3-publish.yml
+++ b/.github/workflows/generator-generic-ossf-slsa3-publish.yml
@@ -2,6 +2,7 @@ name: SLSA Generic Provenance
 
 on:
   workflow_dispatch:
+
   release:
     types:
       - created
@@ -27,23 +28,43 @@ jobs:
           go-version-file: go.mod
           cache: true
 
+      - name: Verify Go version
+        run: go version
+
       - name: Download dependencies
         run: go mod download
 
       - name: Verify dependencies
         run: go mod verify
 
+      - name: Check formatting
+        shell: bash
+        run: |
+          files="$(gofmt -l .)"
+
+          if [ -n "$files" ]; then
+            echo "::error::The following files are not formatted:"
+            echo "$files"
+            exit 1
+          fi
+
+      - name: Run go vet
+        run: go vet ./...
+
       - name: Build
         run: go build -v ./...
 
       - name: Test
-        run: go test ./...
+        run: go test -v ./...
+
+      - name: Run race detector
+        run: go test -race ./...
 
       - name: Create source archive
         run: |
           git archive \
             --format=tar.gz \
-            --output=codemeet-go-${GITHUB_REF_NAME}.tar.gz \
+            --output="codemeet-go-${GITHUB_REF_NAME}.tar.gz" \
             "${GITHUB_SHA}"
 
       - name: Generate provenance subjects
@@ -59,6 +80,12 @@ jobs:
           echo "digests=$(sha256sum \
             "codemeet-go-${GITHUB_REF_NAME}.tar.gz" \
             | base64 -w0)" >> "${GITHUB_OUTPUT}"
+
+      - name: Upload checksums
+        uses: actions/upload-artifact@v4
+        with:
+          name: checksums
+          path: checksums.txt
 
   provenance:
     name: Generate SLSA Provenance
